sonar.projectKey=cerbero90_laravel-enum
sonar.projectName=Laravel Enum
sonar.organization=cerbero

sonar.sources=src
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=tests-report.xml
